//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnytimeMaintenanceWindow) DeepCopyInto(out *AnytimeMaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnytimeMaintenanceWindow.
func (in *AnytimeMaintenanceWindow) DeepCopy() *AnytimeMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(AnytimeMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cilium) DeepCopyInto(out *Cilium) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cilium.
func (in *Cilium) DeepCopy() *Cilium {
	if in == nil {
		return nil
	}
	out := new(Cilium)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservation) DeepCopyInto(out *ClusterObservation) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InternetGateway != nil {
		in, out := &in.InternetGateway, &out.InternetGateway
		*out = new(Cluster_GatewayIpv4Address)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicy)
		**out = **in
	}
	if in.Master != nil {
		in, out := &in.Master, &out.Master
		*out = new(Master)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservation.
func (in *ClusterObservation) DeepCopy() *ClusterObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NetworkIDRef != nil {
		in, out := &in.NetworkIDRef, &out.NetworkIDRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.NetworkIDSelector != nil {
		in, out := &in.NetworkIDSelector, &out.NetworkIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterSpec != nil {
		in, out := &in.MasterSpec, &out.MasterSpec
		*out = new(MasterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IpAllocationPolicy != nil {
		in, out := &in.IpAllocationPolicy, &out.IpAllocationPolicy
		*out = new(IPAllocationPolicy)
		**out = **in
	}
	if in.InternetGateway != nil {
		in, out := &in.InternetGateway, &out.InternetGateway
		*out = new(Cluster_GatewayIpv4Address)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicy)
		**out = **in
	}
	if in.KmsProvider != nil {
		in, out := &in.KmsProvider, &out.KmsProvider
		*out = new(KMSProvider)
		**out = **in
	}
	if in.NetworkImplementation != nil {
		in, out := &in.NetworkImplementation, &out.NetworkImplementation
		*out = new(Cluster_Cilium)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster_Cilium) DeepCopyInto(out *Cluster_Cilium) {
	*out = *in
	if in.Cilium != nil {
		in, out := &in.Cilium, &out.Cilium
		*out = new(Cilium)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_Cilium.
func (in *Cluster_Cilium) DeepCopy() *Cluster_Cilium {
	if in == nil {
		return nil
	}
	out := new(Cluster_Cilium)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster_GatewayIpv4Address) DeepCopyInto(out *Cluster_GatewayIpv4Address) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_GatewayIpv4Address.
func (in *Cluster_GatewayIpv4Address) DeepCopy() *Cluster_GatewayIpv4Address {
	if in == nil {
		return nil
	}
	out := new(Cluster_GatewayIpv4Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyMaintenanceWindow) DeepCopyInto(out *DailyMaintenanceWindow) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(TimeOfDay)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyMaintenanceWindow.
func (in *DailyMaintenanceWindow) DeepCopy() *DailyMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(DailyMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaysOfWeekMaintenanceWindow) DeepCopyInto(out *DaysOfWeekMaintenanceWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(TimeOfDay)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaysOfWeekMaintenanceWindow.
func (in *DaysOfWeekMaintenanceWindow) DeepCopy() *DaysOfWeekMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(DaysOfWeekMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Duration) DeepCopyInto(out *Duration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Duration.
func (in *Duration) DeepCopy() *Duration {
	if in == nil {
		return nil
	}
	out := new(Duration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAddressSpec) DeepCopyInto(out *ExternalAddressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAddressSpec.
func (in *ExternalAddressSpec) DeepCopy() *ExternalAddressSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationPolicy) DeepCopyInto(out *IPAllocationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationPolicy.
func (in *IPAllocationPolicy) DeepCopy() *IPAllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(IPAllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalAddressSpec) DeepCopyInto(out *InternalAddressSpec) {
	*out = *in
	if in.SubnetIDRef != nil {
		in, out := &in.SubnetIDRef, &out.SubnetIDRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.SubnetIDSelector != nil {
		in, out := &in.SubnetIDSelector, &out.SubnetIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalAddressSpec.
func (in *InternalAddressSpec) DeepCopy() *InternalAddressSpec {
	if in == nil {
		return nil
	}
	out := new(InternalAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMSProvider) DeepCopyInto(out *KMSProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMSProvider.
func (in *KMSProvider) DeepCopy() *KMSProvider {
	if in == nil {
		return nil
	}
	out := new(KMSProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(MaintenanceWindow_Policy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow_Policy) DeepCopyInto(out *MaintenanceWindow_Policy) {
	*out = *in
	if in.Anytime != nil {
		in, out := &in.Anytime, &out.Anytime
		*out = new(AnytimeMaintenanceWindow)
		**out = **in
	}
	if in.DailyMaintenanceWindow != nil {
		in, out := &in.DailyMaintenanceWindow, &out.DailyMaintenanceWindow
		*out = new(DailyMaintenanceWindow)
		(*in).DeepCopyInto(*out)
	}
	if in.WeeklyMaintenanceWindow != nil {
		in, out := &in.WeeklyMaintenanceWindow, &out.WeeklyMaintenanceWindow
		*out = new(WeeklyMaintenanceWindow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow_Policy.
func (in *MaintenanceWindow_Policy) DeepCopy() *MaintenanceWindow_Policy {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow_Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Master) DeepCopyInto(out *Master) {
	*out = *in
	if in.MasterType != nil {
		in, out := &in.MasterType, &out.MasterType
		*out = new(Master_MasterType)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenancePolicy != nil {
		in, out := &in.MaintenancePolicy, &out.MaintenancePolicy
		*out = new(MasterMaintenancePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Master.
func (in *Master) DeepCopy() *Master {
	if in == nil {
		return nil
	}
	out := new(Master)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterLocation) DeepCopyInto(out *MasterLocation) {
	*out = *in
	if in.InternalV4AddressSpec != nil {
		in, out := &in.InternalV4AddressSpec, &out.InternalV4AddressSpec
		*out = new(InternalAddressSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterLocation.
func (in *MasterLocation) DeepCopy() *MasterLocation {
	if in == nil {
		return nil
	}
	out := new(MasterLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterMaintenancePolicy) DeepCopyInto(out *MasterMaintenancePolicy) {
	*out = *in
	if in.MaintenanceWindow != nil {
		in, out := &in.MaintenanceWindow, &out.MaintenanceWindow
		*out = new(MaintenanceWindow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterMaintenancePolicy.
func (in *MasterMaintenancePolicy) DeepCopy() *MasterMaintenancePolicy {
	if in == nil {
		return nil
	}
	out := new(MasterMaintenancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterSpec) DeepCopyInto(out *MasterSpec) {
	*out = *in
	if in.MasterType != nil {
		in, out := &in.MasterType, &out.MasterType
		*out = new(MasterSpec_MasterType)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenancePolicy != nil {
		in, out := &in.MaintenancePolicy, &out.MaintenancePolicy
		*out = new(MasterMaintenancePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterSpec.
func (in *MasterSpec) DeepCopy() *MasterSpec {
	if in == nil {
		return nil
	}
	out := new(MasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterSpec_MasterType) DeepCopyInto(out *MasterSpec_MasterType) {
	*out = *in
	if in.ZonalMasterSpec != nil {
		in, out := &in.ZonalMasterSpec, &out.ZonalMasterSpec
		*out = new(ZonalMasterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionalMasterSpec != nil {
		in, out := &in.RegionalMasterSpec, &out.RegionalMasterSpec
		*out = new(RegionalMasterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterSpec_MasterType.
func (in *MasterSpec_MasterType) DeepCopy() *MasterSpec_MasterType {
	if in == nil {
		return nil
	}
	out := new(MasterSpec_MasterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterUpdateSpec) DeepCopyInto(out *MasterUpdateSpec) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(UpdateVersionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenancePolicy != nil {
		in, out := &in.MaintenancePolicy, &out.MaintenancePolicy
		*out = new(MasterMaintenancePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityGroupIds != nil {
		in, out := &in.SecurityGroupIds, &out.SecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterUpdateSpec.
func (in *MasterUpdateSpec) DeepCopy() *MasterUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(MasterUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Master_MasterType) DeepCopyInto(out *Master_MasterType) {
	*out = *in
	if in.ZonalMaster != nil {
		in, out := &in.ZonalMaster, &out.ZonalMaster
		*out = new(ZonalMaster)
		**out = **in
	}
	if in.RegionalMaster != nil {
		in, out := &in.RegionalMaster, &out.RegionalMaster
		*out = new(RegionalMaster)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Master_MasterType.
func (in *Master_MasterType) DeepCopy() *Master_MasterType {
	if in == nil {
		return nil
	}
	out := new(Master_MasterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalMaster) DeepCopyInto(out *RegionalMaster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalMaster.
func (in *RegionalMaster) DeepCopy() *RegionalMaster {
	if in == nil {
		return nil
	}
	out := new(RegionalMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalMasterSpec) DeepCopyInto(out *RegionalMasterSpec) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]*MasterLocation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MasterLocation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ExternalV4AddressSpec != nil {
		in, out := &in.ExternalV4AddressSpec, &out.ExternalV4AddressSpec
		*out = new(ExternalAddressSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalMasterSpec.
func (in *RegionalMasterSpec) DeepCopy() *RegionalMasterSpec {
	if in == nil {
		return nil
	}
	out := new(RegionalMasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Specifier) DeepCopyInto(out *Specifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Specifier.
func (in *Specifier) DeepCopy() *Specifier {
	if in == nil {
		return nil
	}
	out := new(Specifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeOfDay) DeepCopyInto(out *TimeOfDay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeOfDay.
func (in *TimeOfDay) DeepCopy() *TimeOfDay {
	if in == nil {
		return nil
	}
	out := new(TimeOfDay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateVersionSpec) DeepCopyInto(out *UpdateVersionSpec) {
	*out = *in
	if in.Specifier != nil {
		in, out := &in.Specifier, &out.Specifier
		*out = new(Specifier)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateVersionSpec.
func (in *UpdateVersionSpec) DeepCopy() *UpdateVersionSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeeklyMaintenanceWindow) DeepCopyInto(out *WeeklyMaintenanceWindow) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]*DaysOfWeekMaintenanceWindow, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DaysOfWeekMaintenanceWindow)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeeklyMaintenanceWindow.
func (in *WeeklyMaintenanceWindow) DeepCopy() *WeeklyMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(WeeklyMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZonalMaster) DeepCopyInto(out *ZonalMaster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZonalMaster.
func (in *ZonalMaster) DeepCopy() *ZonalMaster {
	if in == nil {
		return nil
	}
	out := new(ZonalMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZonalMasterSpec) DeepCopyInto(out *ZonalMasterSpec) {
	*out = *in
	if in.InternalV4AddressSpec != nil {
		in, out := &in.InternalV4AddressSpec, &out.InternalV4AddressSpec
		*out = new(InternalAddressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalV4AddressSpec != nil {
		in, out := &in.ExternalV4AddressSpec, &out.ExternalV4AddressSpec
		*out = new(ExternalAddressSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZonalMasterSpec.
func (in *ZonalMasterSpec) DeepCopy() *ZonalMasterSpec {
	if in == nil {
		return nil
	}
	out := new(ZonalMasterSpec)
	in.DeepCopyInto(out)
	return out
}
