apiVersion: networking.yc.yandex-team.ru/v1alpha1
kind: Subnet
metadata:
  name: yc-subnet
spec:
  forProvider:
    name: subnet-from-kuber
    folder_id: b1gjmmtufqjb87p5tojj
    network_name: network-from-kuber
    zone_id: ru-central1-a
    v4_cidr_blocks:
      - 10.5.15.0/24
    description: "yc subnet created via kubectl"
  providerConfigRef:
    name: test-yc
